### ISSUE TITLE
Exclude routes from keycloak auth

### ISSUE THREAD

**Issue by clabnet** [britto-andre/scaffold_python_services_project#7]
Hi @britto-andre,
I know that you using waza-ari/fastapi-keycloak-middleware, it run successfully ?

My server is provide of swagger documentation pages  `http://localhost:5005/swagger`
I would exclude auth for swagger routes.

I added the `excluded_patterns` on config as is but it seems not working.
```
keycloak_config = KeycloakConfiguration(
   ...
    exclude_patterns=["swagger"],
)
```
The message is `Your request is missing an 'Authorization' HTTP header`.

Have you any idea to bypass auth for certains routes ?

Thank's in advance

**Comment by britto-andre** [comment]
Tks @clabnet .

It's work!
